config/routes.rb
Rails.application.routes.draw do
  resources :seijikas
  resources :manifestos

  root "main#main"

end

app/models/manifesto.rb
class Manifesto < ActiveRecord::Base
  belongs_to :manifesto_type
  belongs_to :pref
  belongs_to :mypolicy1field1, class_name:"SeisakuBunya",foreign_key:"mypolicy1field1_id", primary_key:"id"
  belongs_to :mypolicy1field2, class_name:"SeisakuBunya",foreign_key:"mypolicy1field2_id", primary_key:"id"
  belongs_to :mypolicy1field3, class_name:"SeisakuBunya",foreign_key:"mypolicy1field3_id", primary_key:"id"
  belongs_to :mypolicy2field1, class_name:"SeisakuBunya",foreign_key:"mypolicy2field1_id", primary_key:"id"
  belongs_to :mypolicy2field2, class_name:"SeisakuBunya",foreign_key:"mypolicy2field2_id", primary_key:"id"
  belongs_to :mypolicy2field3, class_name:"SeisakuBunya",foreign_key:"mypolicy2field3_id", primary_key:"id"
  belongs_to :mypolicy3field1, class_name:"SeisakuBunya",foreign_key:"mypolicy3field1_id", primary_key:"id"
  belongs_to :mypolicy3field2, class_name:"SeisakuBunya",foreign_key:"mypolicy3field2_id", primary_key:"id"
  belongs_to :mypolicy3field3, class_name:"SeisakuBunya",foreign_key:"mypolicy3field3_id", primary_key:"id"
end

app/models/manifesto_type.rb
class ManifestoType < ActiveRecord::Base
end

app/models/pref.rb
class Pref < ActiveRecord::Base
end

app/models/seijika.rb
class Seijika < ActiveRecord::Base
end

app/models/seisaku_bunya.rb
class SeisakuBunya < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def main
  end
end

app/controllers/manifestos_controller.rb
class ManifestosController < ApplicationController
  before_action :set_manifesto, only: [:show, :edit, :update, :destroy]

  # GET /manifestos
  # GET /manifestos.json
  def index
    @manifestos = Manifesto.all
  end

  # GET /manifestos/1
  # GET /manifestos/1.json
  def show
  end

  # GET /manifestos/new
  def new
    @manifesto = Manifesto.new
  end

  # GET /manifestos/1/edit
  def edit
  end

  # POST /manifestos
  # POST /manifestos.json
  def create
    @manifesto = Manifesto.new(manifesto_params)

    respond_to do |format|
      if @manifesto.save
        format.html { redirect_to @manifesto, notice: 'Manifesto was successfully created.' }
        format.json { render :show, status: :created, location: @manifesto }
      else
        format.html { render :new }
        format.json { render json: @manifesto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manifestos/1
  # PATCH/PUT /manifestos/1.json
  def update
    respond_to do |format|
      if @manifesto.update(manifesto_params)
        format.html { redirect_to @manifesto, notice: 'Manifesto was successfully updated.' }
        format.json { render :show, status: :ok, location: @manifesto }
      else
        format.html { render :edit }
        format.json { render json: @manifesto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manifestos/1
  # DELETE /manifestos/1.json
  def destroy
    @manifesto.destroy
    respond_to do |format|
      format.html { redirect_to manifestos_url, notice: 'Manifesto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manifesto
      @manifesto = Manifesto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manifesto_params
      params.require(:manifesto).permit(:manifesto_type_id, :is_open, :name, :name_kana, :pref_id, :area, :reason, :vision, :theme, :mypolicy1field1, :mypolicy1field2, :mypolicy1field3, :mypolicy1content, :mypolicy2field1, :mypolicy2field2, :mypolicy2field3, :mypolicy2content, :mypolicy3field1, :mypolicy3field2, :mypolicy3field3, :mypolicy3content, :policyfield1, :policyfield2, :policyfield3, :policyfield4, :policyfield5, :policyfield6, :policyfield7, :policyfield8, :policyfield9, :policyfield10, :kensyo, :file_nae, :acccept, :senkyoku, :senkyoname, :topic1_1cont, :topic1_1term, :topic1_1goal, :topic1_1reso, :topic1_2cont, :topic1_2term, :topic1_2goal, :topic1_2reso, :topic1_3cont, :topic1_3term, :topic1_3goal, :topic1_3reso, :topic2_1cont, :topic2_1term, :topic2_1goal, :topic2_1reso, :topic2_2cont, :topic2_2term, :topic2_2goal, :topic2_2reso, :topic2_3cont, :topic2_3term, :topic2_3goal, :topic2_3reso, :topic3_1cont, :topic3_1term, :topic3_1goal, :topic3_1reso, :topic3_2cont, :topic3_2term, :topic3_2goal, :topic3_2reso, :topic3_3cont, :topic3_3term, :topic3_3goal, :topic3_3reso, :assem_act1, :assem_act2, :assem_act3, :url_, :photo, :geo, :policyfieldsum)
    end
end

app/controllers/seijikas_controller.rb
class SeijikasController < ApplicationController
  before_action :set_seijika, only: [:show, :edit, :update, :destroy]

  # GET /seijikas
  # GET /seijikas.json
  def index
    @seijikas = Seijika.all
  end

  # GET /seijikas/1
  # GET /seijikas/1.json
  def show
  end

  # GET /seijikas/new
  def new
    @seijika = Seijika.new
  end

  # GET /seijikas/1/edit
  def edit
  end

  # POST /seijikas
  # POST /seijikas.json
  def create
    @seijika = Seijika.new(seijika_params)

    respond_to do |format|
      if @seijika.save
        format.html { redirect_to @seijika, notice: 'Seijika was successfully created.' }
        format.json { render :show, status: :created, location: @seijika }
      else
        format.html { render :new }
        format.json { render json: @seijika.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seijikas/1
  # PATCH/PUT /seijikas/1.json
  def update
    respond_to do |format|
      if @seijika.update(seijika_params)
        format.html { redirect_to @seijika, notice: 'Seijika was successfully updated.' }
        format.json { render :show, status: :ok, location: @seijika }
      else
        format.html { render :edit }
        format.json { render json: @seijika.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seijikas/1
  # DELETE /seijikas/1.json
  def destroy
    @seijika.destroy
    respond_to do |format|
      format.html { redirect_to seijikas_url, notice: 'Seijika was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seijika
      @seijika = Seijika.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seijika_params
      params.require(:seijika).permit(:user_type, :sei, :mei, :seikana, :meikana, :sei_roma, :mei_roma, :mail1, :mail2, :birthday, :tel, :password, :pref, :sex_, :photo, :website_url, :blog_url, :twitter, :facebook, :movie, :certification, :certificated_at, :city, :office_zip, :office_pref, :office_city, :office_address, :office_building, :office_tel, :ofice_mobile)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/manifestos_helper.rb
module ManifestosHelper
end

app/helpers/seijikas_helper.rb
module SeijikasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mswitch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/main.html.erb
<html>
<body>
<h1>
  マニフェストスイッチ
</h1>
<h2>
  登録情報一覧
</h2>
<p><a href="/manifestos">マニフェスト一覧</a></p>
<p><a href="/seijikas">政治家一覧</a></p>

<h2>新規登録する</h2>
<p><a href="/manifestos/new">マニフェストを新規登録する</a></p>


</body>
</html>

app/views/manifestos/edit.html.erb
<h1>Editing Manifesto</h1>

<%= render 'form' %>

<%= link_to 'Show', @manifesto %> |
<%= link_to 'Back', manifestos_path %>

app/views/manifestos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Manifestos</h1>

<table>
  <thead>
    <tr>
      <th><%= t('activerecord.attributes.manifesto.manifesto_type') %></th>
      <th><%= t('activerecord.attributes.manifesto.is_open') %></th>
      <th><%= t('activerecord.attributes.manifesto.name') %></th>
      <th><%= t('activerecord.attributes.manifesto.name_kana') %></th>
      <th><%= t('activerecord.attributes.manifesto.pref') %></th>
      <th><%= t('activerecord.attributes.manifesto.area') %></th>
      <th width="200px"><%= t('activerecord.attributes.manifesto.reason') %></th>
      <th width="200px"><%= t('activerecord.attributes.manifesto.vision') %></th>
      <th width="200px"><%= t('activerecord.attributes.manifesto.theme') %></th>
      <th><%= t('activerecord.attributes.manifesto.mypolicy1field1') %></th>
      <th><%= t('activerecord.attributes.manifesto.mypolicy1field2') %></th>
      <th><%= t('activerecord.attributes.manifesto.mypolicy1field3') %></th>
      <th><%= t('activerecord.attributes.manifesto.mypolicy1content') %></th>
      <th><%= t('activerecord.attributes.manifesto.mypolicy2field1') %></th>
      <th><%= t('activerecord.attributes.manifesto.mypolicy2field2') %></th>
      <th><%= t('activerecord.attributes.manifesto.mypolicy2field3') %></th>
      <th><%= t('activerecord.attributes.manifesto.mypolicy2content') %></th>
      <th><%= t('activerecord.attributes.manifesto.mypolicy3field1') %></th>
      <th><%= t('activerecord.attributes.manifesto.mypolicy3field2') %></th>
      <th><%= t('activerecord.attributes.manifesto.mypolicy3field3') %></th>
      <th><%= t('activerecord.attributes.manifesto.mypolicy3content') %></th>
      <th><%= t('activerecord.attributes.manifesto.policyfield1') %></th>
      <th><%= t('activerecord.attributes.manifesto.policyfield2') %></th>
      <th><%= t('activerecord.attributes.manifesto.policyfield3') %></th>
      <th><%= t('activerecord.attributes.manifesto.policyfield4') %></th>
      <th><%= t('activerecord.attributes.manifesto.policyfield5') %></th>
      <th><%= t('activerecord.attributes.manifesto.policyfield6') %></th>
      <th><%= t('activerecord.attributes.manifesto.policyfield7') %></th>
      <th><%= t('activerecord.attributes.manifesto.policyfield8') %></th>
      <th><%= t('activerecord.attributes.manifesto.policyfield9') %></th>
      <th><%= t('activerecord.attributes.manifesto.policyfield10') %></th>
      <th><%= t('activerecord.attributes.manifesto.kensyo') %></th>
      <th><%= t('activerecord.attributes.manifesto.file_name') %></th>
      <th><%= t('activerecord.attributes.manifesto.acccept') %></th>
      <th><%= t('activerecord.attributes.manifesto.senkyoku') %></th>
      <th><%= t('activerecord.attributes.manifesto.senkyoname') %></th>
      <!--th>Topic1 1cont</th>
      <th>Topic1 1term</th>
      <th>Topic1 1goal</th>
      <th>Topic1 1reso</th>
      <th>Topic1 2cont</th>
      <th>Topic1 2term</th>
      <th>Topic1 2goal</th>
      <th>Topic1 2reso</th>
      <th>Topic1 3cont</th>
      <th>Topic1 3term</th>
      <th>Topic1 3goal</th>
      <th>Topic1 3reso</th>
      <th>Topic2 1cont</th>
      <th>Topic2 1term</th>
      <th>Topic2 1goal</th>
      <th>Topic2 1reso</th>
      <th>Topic2 2cont</th>
      <th>Topic2 2term</th>
      <th>Topic2 2goal</th>
      <th>Topic2 2reso</th>
      <th>Topic2 3cont</th>
      <th>Topic2 3term</th>
      <th>Topic2 3goal</th>
      <th>Topic2 3reso</th>
      <th>Topic3 1cont</th>
      <th>Topic3 1term</th>
      <th>Topic3 1goal</th>
      <th>Topic3 1reso</th>
      <th>Topic3 2cont</th>
      <th>Topic3 2term</th>
      <th>Topic3 2goal</th>
      <th>Topic3 2reso</th>
      <th>Topic3 3cont</th>
      <th>Topic3 3term</th>
      <th>Topic3 3goal</th>
      <th>Topic3 3reso</th>
      <th>Assem act1</th>
      <th>Assem act2</th>
      <th>Assem act3</th>
      <th>Url </th>
      <th>Photo</th>
      <th>Geo</th>
      <th>Policyfieldsum</th-->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @manifestos.each do |manifesto| %>
      <tr>
        <td><%= manifesto.manifesto_type.name %></td>
        <td><%= manifesto.is_open %></td>
        <td><%= manifesto.name %></td>
        <td><%= manifesto.name_kana %></td>
        <td><%= manifesto.pref.name %></td>
        <td><%= manifesto.area %></td>
        <td><%= manifesto.reason[0,100] %></td>
        <td><%= manifesto.vision[0,100] %></td>
        <td><%= manifesto.theme[0,100] %></td>
        <td><%= manifesto.mypolicy1field1.try(:name) || "" %></td>
        <td><%= manifesto.mypolicy1field2.try(:name) || "" %></td>
        <td><%= manifesto.mypolicy1field3.try(:name) || "" %></td>
        <td><%= manifesto.mypolicy1content %></td>
        <td><%= manifesto.mypolicy2field1.try(:name) || "" %></td>
        <td><%= manifesto.mypolicy2field2.try(:name) || "" %></td>
        <td><%= manifesto.mypolicy2field3.try(:name) || "" %></td>
        <td><%= manifesto.mypolicy2content %></td>
        <td><%= manifesto.mypolicy3field1.try(:name) || "" %></td>
        <td><%= manifesto.mypolicy3field2.try(:name) || "" %></td>
        <td><%= manifesto.mypolicy3field3.try(:name) || "" %></td>
        <td><%= manifesto.mypolicy3content %></td>
        <td><%= manifesto.policyfield1 %></td>
        <td><%= manifesto.policyfield2 %></td>
        <td><%= manifesto.policyfield3 %></td>
        <td><%= manifesto.policyfield4 %></td>
        <td><%= manifesto.policyfield5 %></td>
        <td><%= manifesto.policyfield6 %></td>
        <td><%= manifesto.policyfield7 %></td>
        <td><%= manifesto.policyfield8 %></td>
        <td><%= manifesto.policyfield9 %></td>
        <td><%= manifesto.policyfield10 %></td>
        <td><%= manifesto.kensyo %></td>
        <td><%= manifesto.file_name %></td>
        <td><%= manifesto.acccept %></td>
        <td><%= manifesto.senkyoku %></td>
        <td><%= manifesto.senkyoname %></td>
        <!--td><%= manifesto.topic1_1cont %></td>
        <td><%= manifesto.topic1_1term %></td>
        <td><%= manifesto.topic1_1goal %></td>
        <td><%= manifesto.topic1_1reso %></td>
        <td><%= manifesto.topic1_2cont %></td>
        <td><%= manifesto.topic1_2term %></td>
        <td><%= manifesto.topic1_2goal %></td>
        <td><%= manifesto.topic1_2reso %></td>
        <td><%= manifesto.topic1_3cont %></td>
        <td><%= manifesto.topic1_3term %></td>
        <td><%= manifesto.topic1_3goal %></td>
        <td><%= manifesto.topic1_3reso %></td>
        <td><%= manifesto.topic2_1cont %></td>
        <td><%= manifesto.topic2_1term %></td>
        <td><%= manifesto.topic2_1goal %></td>
        <td><%= manifesto.topic2_1reso %></td>
        <td><%= manifesto.topic2_2cont %></td>
        <td><%= manifesto.topic2_2term %></td>
        <td><%= manifesto.topic2_2goal %></td>
        <td><%= manifesto.topic2_2reso %></td>
        <td><%= manifesto.topic2_3cont %></td>
        <td><%= manifesto.topic2_3term %></td>
        <td><%= manifesto.topic2_3goal %></td>
        <td><%= manifesto.topic2_3reso %></td>
        <td><%= manifesto.topic3_1cont %></td>
        <td><%= manifesto.topic3_1term %></td>
        <td><%= manifesto.topic3_1goal %></td>
        <td><%= manifesto.topic3_1reso %></td>
        <td><%= manifesto.topic3_2cont %></td>
        <td><%= manifesto.topic3_2term %></td>
        <td><%= manifesto.topic3_2goal %></td>
        <td><%= manifesto.topic3_2reso %></td>
        <td><%= manifesto.topic3_3cont %></td>
        <td><%= manifesto.topic3_3term %></td>
        <td><%= manifesto.topic3_3goal %></td>
        <td><%= manifesto.topic3_3reso %></td>
        <td><%= manifesto.assem_act1 %></td>
        <td><%= manifesto.assem_act2 %></td>
        <td><%= manifesto.assem_act3 %></td>
        <td><%= manifesto.url_ %></td>
        <td><%= manifesto.photo %></td>
        <td><%= manifesto.geo %></td>
        <td><%= manifesto.policyfieldsum %></td-->
        <td><%= link_to 'Show', manifesto %></td>
        <td><%= link_to 'Edit', edit_manifesto_path(manifesto) %></td>
        <td><%= link_to 'Destroy', manifesto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manifesto', new_manifesto_path %>

app/views/manifestos/new.html.erb
<h1>New Manifesto</h1>

<%= render 'form' %>

<%= link_to 'Back', manifestos_path %>

app/views/manifestos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Manifesto type:</strong>
  <%= @manifesto.manifesto_type %>
</p>

<p>
  <strong>Is open:</strong>
  <%= @manifesto.is_open %>
</p>

<p>
  <strong>Name:</strong>
  <%= @manifesto.name %>
</p>

<p>
  <strong>Name kana:</strong>
  <%= @manifesto.name_kana %>
</p>

<p>
  <strong>Pref:</strong>
  <%= @manifesto.pref %>
</p>

<p>
  <strong>Area:</strong>
  <%= @manifesto.area %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @manifesto.reason %>
</p>

<p>
  <strong>Vision:</strong>
  <%= @manifesto.vision %>
</p>

<p>
  <strong>Theme:</strong>
  <%= @manifesto.theme %>
</p>

<p>
  <strong>Mypolicy1field1:</strong>
  <%= @manifesto.mypolicy1field1 %>
</p>

<p>
  <strong>Mypolicy1field2:</strong>
  <%= @manifesto.mypolicy1field2 %>
</p>

<p>
  <strong>Mypolicy1field3:</strong>
  <%= @manifesto.mypolicy1field3 %>
</p>

<p>
  <strong>Mypolicy1content:</strong>
  <%= @manifesto.mypolicy1content %>
</p>

<p>
  <strong>Mypolicy2field1:</strong>
  <%= @manifesto.mypolicy2field1 %>
</p>

<p>
  <strong>Mypolicy2field2:</strong>
  <%= @manifesto.mypolicy2field2 %>
</p>

<p>
  <strong>Mypolicy2field3:</strong>
  <%= @manifesto.mypolicy2field3 %>
</p>

<p>
  <strong>Mypolicy2content:</strong>
  <%= @manifesto.mypolicy2content %>
</p>

<p>
  <strong>Mypolicy3field1:</strong>
  <%= @manifesto.mypolicy3field1 %>
</p>

<p>
  <strong>Mypolicy3field2:</strong>
  <%= @manifesto.mypolicy3field2 %>
</p>

<p>
  <strong>Mypolicy3field3:</strong>
  <%= @manifesto.mypolicy3field3 %>
</p>

<p>
  <strong>Mypolicy3content:</strong>
  <%= @manifesto.mypolicy3content %>
</p>

<p>
  <strong>Policyfield1:</strong>
  <%= @manifesto.policyfield1 %>
</p>

<p>
  <strong>Policyfield2:</strong>
  <%= @manifesto.policyfield2 %>
</p>

<p>
  <strong>Policyfield3:</strong>
  <%= @manifesto.policyfield3 %>
</p>

<p>
  <strong>Policyfield4:</strong>
  <%= @manifesto.policyfield4 %>
</p>

<p>
  <strong>Policyfield5:</strong>
  <%= @manifesto.policyfield5 %>
</p>

<p>
  <strong>Policyfield6:</strong>
  <%= @manifesto.policyfield6 %>
</p>

<p>
  <strong>Policyfield7:</strong>
  <%= @manifesto.policyfield7 %>
</p>

<p>
  <strong>Policyfield8:</strong>
  <%= @manifesto.policyfield8 %>
</p>

<p>
  <strong>Policyfield9:</strong>
  <%= @manifesto.policyfield9 %>
</p>

<p>
  <strong>Policyfield10:</strong>
  <%= @manifesto.policyfield10 %>
</p>

<p>
  <strong>Kensyo:</strong>
  <%= @manifesto.kensyo %>
</p>

<p>
  <strong>File nae:</strong>
  <%= @manifesto.file_name %>
</p>

<p>
  <strong>Acccept:</strong>
  <%= @manifesto.acccept %>
</p>

<p>
  <strong>Senkyoku:</strong>
  <%= @manifesto.senkyoku %>
</p>

<p>
  <strong>Senkyoname:</strong>
  <%= @manifesto.senkyoname %>
</p>

<p>
  <strong>Topic1 1cont:</strong>
  <%= @manifesto.topic1_1cont %>
</p>

<p>
  <strong>Topic1 1term:</strong>
  <%= @manifesto.topic1_1term %>
</p>

<p>
  <strong>Topic1 1goal:</strong>
  <%= @manifesto.topic1_1goal %>
</p>

<p>
  <strong>Topic1 1reso:</strong>
  <%= @manifesto.topic1_1reso %>
</p>

<p>
  <strong>Topic1 2cont:</strong>
  <%= @manifesto.topic1_2cont %>
</p>

<p>
  <strong>Topic1 2term:</strong>
  <%= @manifesto.topic1_2term %>
</p>

<p>
  <strong>Topic1 2goal:</strong>
  <%= @manifesto.topic1_2goal %>
</p>

<p>
  <strong>Topic1 2reso:</strong>
  <%= @manifesto.topic1_2reso %>
</p>

<p>
  <strong>Topic1 3cont:</strong>
  <%= @manifesto.topic1_3cont %>
</p>

<p>
  <strong>Topic1 3term:</strong>
  <%= @manifesto.topic1_3term %>
</p>

<p>
  <strong>Topic1 3goal:</strong>
  <%= @manifesto.topic1_3goal %>
</p>

<p>
  <strong>Topic1 3reso:</strong>
  <%= @manifesto.topic1_3reso %>
</p>

<p>
  <strong>Topic2 1cont:</strong>
  <%= @manifesto.topic2_1cont %>
</p>

<p>
  <strong>Topic2 1term:</strong>
  <%= @manifesto.topic2_1term %>
</p>

<p>
  <strong>Topic2 1goal:</strong>
  <%= @manifesto.topic2_1goal %>
</p>

<p>
  <strong>Topic2 1reso:</strong>
  <%= @manifesto.topic2_1reso %>
</p>

<p>
  <strong>Topic2 2cont:</strong>
  <%= @manifesto.topic2_2cont %>
</p>

<p>
  <strong>Topic2 2term:</strong>
  <%= @manifesto.topic2_2term %>
</p>

<p>
  <strong>Topic2 2goal:</strong>
  <%= @manifesto.topic2_2goal %>
</p>

<p>
  <strong>Topic2 2reso:</strong>
  <%= @manifesto.topic2_2reso %>
</p>

<p>
  <strong>Topic2 3cont:</strong>
  <%= @manifesto.topic2_3cont %>
</p>

<p>
  <strong>Topic2 3term:</strong>
  <%= @manifesto.topic2_3term %>
</p>

<p>
  <strong>Topic2 3goal:</strong>
  <%= @manifesto.topic2_3goal %>
</p>

<p>
  <strong>Topic2 3reso:</strong>
  <%= @manifesto.topic2_3reso %>
</p>

<p>
  <strong>Topic3 1cont:</strong>
  <%= @manifesto.topic3_1cont %>
</p>

<p>
  <strong>Topic3 1term:</strong>
  <%= @manifesto.topic3_1term %>
</p>

<p>
  <strong>Topic3 1goal:</strong>
  <%= @manifesto.topic3_1goal %>
</p>

<p>
  <strong>Topic3 1reso:</strong>
  <%= @manifesto.topic3_1reso %>
</p>

<p>
  <strong>Topic3 2cont:</strong>
  <%= @manifesto.topic3_2cont %>
</p>

<p>
  <strong>Topic3 2term:</strong>
  <%= @manifesto.topic3_2term %>
</p>

<p>
  <strong>Topic3 2goal:</strong>
  <%= @manifesto.topic3_2goal %>
</p>

<p>
  <strong>Topic3 2reso:</strong>
  <%= @manifesto.topic3_2reso %>
</p>

<p>
  <strong>Topic3 3cont:</strong>
  <%= @manifesto.topic3_3cont %>
</p>

<p>
  <strong>Topic3 3term:</strong>
  <%= @manifesto.topic3_3term %>
</p>

<p>
  <strong>Topic3 3goal:</strong>
  <%= @manifesto.topic3_3goal %>
</p>

<p>
  <strong>Topic3 3reso:</strong>
  <%= @manifesto.topic3_3reso %>
</p>

<p>
  <strong>Assem act1:</strong>
  <%= @manifesto.assem_act1 %>
</p>

<p>
  <strong>Assem act2:</strong>
  <%= @manifesto.assem_act2 %>
</p>

<p>
  <strong>Assem act3:</strong>
  <%= @manifesto.assem_act3 %>
</p>

<p>
  <strong>Url :</strong>
  <%= @manifesto.url_ %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @manifesto.photo %>
</p>

<p>
  <strong>Geo:</strong>
  <%= @manifesto.geo %>
</p>

<p>
  <strong>Policyfieldsum:</strong>
  <%= @manifesto.policyfieldsum %>
</p>

<%= link_to 'Edit', edit_manifesto_path(@manifesto) %> |
<%= link_to 'Back', manifestos_path %>

app/views/seijikas/edit.html.erb
<h1>Editing Seijika</h1>

<%= render 'form' %>

<%= link_to 'Show', @seijika %> |
<%= link_to 'Back', seijikas_path %>

app/views/seijikas/new.html.erb
<h1>New Seijika</h1>

<%= render 'form' %>

<%= link_to 'Back', seijikas_path %>